name: Issue Template
description: Template untuk membuat issue di proyek Next.js
title: "[Issue]: "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Terima kasih telah membuat issue! Silakan isi detail di bawah ini.

  - type: textarea
    id: description
    attributes:
      label: Deskripsi
      description: Jelaskan masalah atau fitur yang ingin ditambahkan.
      placeholder: Deskripsi singkat tentang issue ini...
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Jenis Issue
      description: Pilih jenis issue ini.
      options:
        - Bug Report
        - Feature Request
        - Documentation Update
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Langkah untuk Mereproduksi (untuk Bug Report)
      description: Langkah-langkah untuk mereproduksi bug ini.
      placeholder: Langkah-langkah yang jelas dan terperinci...
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: Perilaku yang Diharapkan (untuk Bug Report)
      description: Apa yang kamu harapkan terjadi?
      placeholder: Perilaku yang diharapkan...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Konteks Tambahan
      description: Informasi tambahan yang mungkin berguna.
      placeholder: Konteks tambahan...
    validations:
      required: false
