name: Penambahan Fitur
description: Template pengusulan fitur baru.
title: "[Fitur]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Deskripsi Fitur
        Jelaskan fitur yang ingin tambahkan.

  - type: textarea
    attributes:
      label: Deskripsi
      description: Penjelasan fitur secara rinci.
      placeholder: Jelaskan fitur yang ingin ditambahkan.
      value: ""
      validations:
        required: true
