name: "Penambahan Fitur"
description: "Gunakan template ini untuk mengajukan fitur baru"
title: "[Fitur] - Judul Fitur"
labels: ["enhancement", "fitur"]
body:
  - type: markdown
    attributes:
      value: "### Deskripsi"
  - type: textarea
    id: deskripsi
    attributes:
      label: Deskripsikan fitur yang ingin ditambahkan
      description: Berikan gambaran tentang fitur dan tujuannya.
  - type: markdown
    attributes:
      value: "### Langkah Pengembangan"
  - type: textarea
    id: langkah
    attributes:
      label: Langkah-langkah
      description: Berikan langkah pengembangan atau task yang diperlukan.
